// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: cowboy.proto

package cowboy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShootRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Damage uint64 `protobuf:"varint,1,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *ShootRequest) Reset() {
	*x = ShootRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cowboy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootRequest) ProtoMessage() {}

func (x *ShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cowboy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootRequest.ProtoReflect.Descriptor instead.
func (*ShootRequest) Descriptor() ([]byte, []int) {
	return file_cowboy_proto_rawDescGZIP(), []int{0}
}

func (x *ShootRequest) GetDamage() uint64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type ShootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ShootResponse) Reset() {
	*x = ShootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cowboy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootResponse) ProtoMessage() {}

func (x *ShootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cowboy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootResponse.ProtoReflect.Descriptor instead.
func (*ShootResponse) Descriptor() ([]byte, []int) {
	return file_cowboy_proto_rawDescGZIP(), []int{1}
}

func (x *ShootResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_cowboy_proto protoreflect.FileDescriptor

var file_cowboy_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x6c, 0x6f, 0x67, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x40,
	0x0a, 0x06, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x12, 0x36, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x12, 0x11, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x53, 0x68,
	0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6c, 0x6f, 0x67,
	0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a,
	0x64, 0x61, 0x72, 0x6f, 0x76, 0x69, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x5f,
	0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x77,
	0x62, 0x6f, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cowboy_proto_rawDescOnce sync.Once
	file_cowboy_proto_rawDescData = file_cowboy_proto_rawDesc
)

func file_cowboy_proto_rawDescGZIP() []byte {
	file_cowboy_proto_rawDescOnce.Do(func() {
		file_cowboy_proto_rawDescData = protoimpl.X.CompressGZIP(file_cowboy_proto_rawDescData)
	})
	return file_cowboy_proto_rawDescData
}

var file_cowboy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cowboy_proto_goTypes = []interface{}{
	(*ShootRequest)(nil),  // 0: log.ShootRequest
	(*ShootResponse)(nil), // 1: log.ShootResponse
}
var file_cowboy_proto_depIdxs = []int32{
	0, // 0: log.Cowboy.HandleShoot:input_type -> log.ShootRequest
	1, // 1: log.Cowboy.HandleShoot:output_type -> log.ShootResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cowboy_proto_init() }
func file_cowboy_proto_init() {
	if File_cowboy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cowboy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cowboy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cowboy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cowboy_proto_goTypes,
		DependencyIndexes: file_cowboy_proto_depIdxs,
		MessageInfos:      file_cowboy_proto_msgTypes,
	}.Build()
	File_cowboy_proto = out.File
	file_cowboy_proto_rawDesc = nil
	file_cowboy_proto_goTypes = nil
	file_cowboy_proto_depIdxs = nil
}
